### ISSUE TITLE
✨ Motor Temperature Telemetry

### ISSUE THREAD

**Issue by gamecocks08** [LemLib/hardware#1]
#### Overview

`Motor::getTemperature()` and `MotorGroup::getTemperatures()`. Gets the temperature of the motor, or a vector of temperatures in the motor group

#### Motivation

Provides telemetry which could be used to prevent motor overheats, for example by operating the robot in a less aggressive manner or by cooling the motors with compressed air

#### Implementation

`Temperature Motor::getTemperature()` gets the temperature of the motor

`std::vector<Temperature> MotorGroup::getTemperatures()` gets the temperature of every motor in the group

**Comment by SizzinSeal** [comment]
Implemented in [e28d038](https://github.com/LemLib/hardware/commit/e28d038becdbfb2eeed945e98c5d7bfb9536ac1b)
